services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SgnDev\ContaoCleverreachBundle\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Migrations,Model,Resources,Tests,Widget}

  SgnDev\ContaoCleverreachBundle\Http\Cleverreach\ApiClient:
    public: false

